### PR TITLE
Dev create post

### PR DESCRIPTION
**Pull request by ajweaver13**
Added a bare-bones post feed to see the posts that were being added to test the create post feature.

### CODE REVIEW

**Review by jamescam — APPROVED** [review]
Approved

**Review by dawmckin — APPROVED** [review]

**Comment by mxledesma** [comment]
Approved

**Review by mxledesma — APPROVED** [review]
Approve all changes

**Review by CJPete22 — CHANGES_REQUESTED** [review]
- app-routing.module.ts: Please remove your "posts" path
- models folder: double check that no one else is using the erased models
- post.service.ts: please delete the commented out code
- profile.service.ts: is it possible to keep the observable looking at just profile?
- please move your files to the profile view so we can keep the file consistent. On the front end the "profile" component refers to the page where we will display the profile and feed as well as create post

**Review by CJPete22 — APPROVED** [review]

**Pull request merged**
