### PR TITLE
Dev like post

### PR DESCRIPTION
**Pull request by ajweaver13**

### CODE REVIEW

**Review by jamescam — APPROVED** [review]
Approved.

**Comment by mxledesma** [comment]
Approve

**Review by mxledesma — APPROVED** [review]

**Review by jamescam — APPROVED** [review]
Approved.

**Review by dawmckin — APPROVED** [review]

**Review by CJPete22 — CHANGES_REQUESTED** [review]
Can you delete the .angular files?
Is it possible to have postLike and deleteLike return a specific type rather than any?
Could you remove the instantiation of the Post value in home.component.ts?

**Review by CJPete22 — CHANGES_REQUESTED** [review]
Your Package-Lock.json appears to still have the materials module in it. Are you still using it?

**Review by CJPete22 — APPROVED** [review]

**Pull request merged**
